//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeDistributor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeDistributor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} x {1} {2} = {3}&lt;/li&gt;.
        /// </summary>
        internal static string LineItemHtml {
            get {
                return ResourceManager.GetString("LineItemHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t{0} x {1} {2} = {3}.
        /// </summary>
        internal static string LineItemText {
            get {
                return ResourceManager.GetString("LineItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Order Receipt for {0}&lt;/h1&gt;
        ///			&lt;ul&gt;
        ///				{1}
        ///			&lt;/ul&gt;
        ///		&lt;h3&gt;Sub-Total: {2}&lt;/h3&gt;
        ///		&lt;h3&gt;Tax: {3}&lt;/h3&gt;
        ///		&lt;h2&gt;Total: {4}&lt;/h3&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ReceiptHtml {
            get {
                return ResourceManager.GetString("ReceiptHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Receipt for {0}
        ///{1}
        ///Sub-Total: {2}
        ///Tax: {3}
        ///Total: {4}.
        /// </summary>
        internal static string ReceiptText {
            get {
                return ResourceManager.GetString("ReceiptText", resourceCulture);
            }
        }
    }
}
